export enum LIST_STEP {
  PERSONAL_INFORMATION = 'PERSONAL_INFORMATION',
  SUBMIT = 'SUBMIT',
  SUBJECT = 'SUBJECT',
  EDUCATION_CERTIFICATION = 'EDUCATION_CERTIFICATION',
  BIOGRAPHY = 'BIOGRAPHY',
  AVAILABILITY = 'AVAILABILITY',
}
